### ISSUE TITLE
Could we have full logs when running ?

### ISSUE THREAD

**Issue by nicolinuxfr** [idleberg/vscode-applescript#10]
I'm not sure it's technically possible, but if it is, it would be really nice to have a full log when running a script.

What I mean by full log, is what the Script Editor.app made by Apple can display when you run a script. For instance, [with this script](https://github.com/nicolinuxfr/full-images/blob/master/full-images.applescript), here's what the Apple app gives me when I run : 

```
tell application "Safari"
	activate
end tell
tell application "System Events"
	get name of process 1 whose frontmost = true
end tell
tell application "Safari"
	get URL of current tab of window 1
end tell
tell current application
	do shell script "echo 'https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2-700x467.jpg' | grep -o '\\-[0-9]\\+x[0-9]\\+'"
	do shell script "echo 'https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2-700x467.jpg' | grep -o '\\-[0-9]\\+x[0-9]\\+'"
	do shell script "curl -s -L -o /dev/null -I -w \"%{http_code}\" 'https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2.jpg'"
	(*https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2.jpg*)
end tell
tell application "Safari"
	close current tab of window 1
	open location "https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2.jpg"
end tell
```

In contrast, here's what Visual Studio Code gives me, the only log in the script : 

```
[Running] osascript "/Users/nicolas/Git/perso/full-images/full-images.applescript"
https://voiretmanger.fr/wp-content/uploads/2017/08/handmaids-tale-saison-2.jpg

[Done] exited with code=0 in 0.601 seconds
```

The full log is far more useful to see what happens and debugs the script. In many case, the log commands are not even necessary, while I have to use it constantly with VSCode.

So, again, if possible, would be great.

Anyway, thanks for your work on this extension ! 👍

**Comment by idleberg** [comment]
In your settings, set `applescript.alwaysShowOutput` to `true`

**Comment by nicolinuxfr** [comment]
It is already set as such. :-)

I thought the setting was only to always display output even if there is no error or nothing to display. I don't think it changes the behaviour of the output itself.

**Comment by idleberg** [comment]
What happens if you run the following piece of code?

```applescript
do shell script "echo 'Hello host'"
tell current application
	do shell script "echo 'Hello current application'"
end tell
tell application "Safari"
end tell
tell current application
	do shell script "echo 'Hello Safari'"
end tell
```

No matter where I run this – AppleScript Editor or Visual Studio Code – it always output "Hello Safari". I'm using macOS 10.13.3 (17G65).

**Comment by nicolinuxfr** [comment]
Sorry, I forgot to answer.

In order to see full logs in the Script Editor.app, you need to check this icon before executing the script. Then, this is what you will have :

![capture d ecran 2018-08-08 a 18 10 37](https://user-images.githubusercontent.com/2078386/43849789-898b327a-9b36-11e8-9e0e-2f57add23c31.png)

I don't know if it's an exclusive feature of this app or if you can have the same in VSCode.
