### ISSUE TITLE
Compile a run-only script or app ?

### ISSUE THREAD

**Issue by nicolinuxfr** [idleberg/vscode-applescript#11]
The Script Editor app has an option to export a run-only script or app. When used, the script can only be runned, the source can not be read or modified.

![capture d ecran 2018-08-08 a 18 23 37](https://user-images.githubusercontent.com/2078386/43850443-3af86e0a-9b38-11e8-9743-990ca9d21423.png)

 If it is possible, could we have a similar option when compiling a script from Visual Studio Code ?

**Comment by idleberg** [comment]
You're probably using a different macOS version than I am. No matter which file format I choose, I never see the *Run-only* option. From the manual page:

```
     -x    Save the resulting script as execute-only.

     The following options are only relevant when creating a new bundled applet or droplet:

     -s    Stay-open applet.

     -u    Use startup screen.
```

I wonder if `-x` works for all or just script file. Could you give me feedback on how your Script Editor behaves for scripts, applications and script bundles?

**Comment by nicolinuxfr** [comment]
Thanks !

I’m not sure I understand however : how can I configure the extension ?

**Comment by idleberg** [comment]
![demo](https://user-images.githubusercontent.com/1504938/43995797-d22d3d44-9db5-11e8-8fd5-4fafa209667d.gif)

**Comment by nicolinuxfr** [comment]
Oh okay I had not seen the update. Great news, I will try this setting. 

Thanks again for your work ! 🙏

**Comment by idleberg** [comment]
If your setup changes with projects, you can now use the new *Create Build Task* command to create Visual Studio tasks that are easy to edit.

**Comment by nicolinuxfr** [comment]
Wow, thanks, I was not expecting that ! I discovered VSCode tasks with your update, and I was able to create a task that exports every script I have in the right directory. 

So it is now much quicker than using the standard Script Editor app. 👍
