### ISSUE TITLE
Go to symbol for AppleScript ?

### ISSUE THREAD

**Issue by nicolinuxfr** [idleberg/vscode-applescript#12]
One feature missing in Visual Studio Code for AppleScript files is the ability to go to a symbol. It would be useful to have this feature to navigate in long scripts, from a function to the next or to jump to a specific function in the file.

I don't know if it is possible, but if that's the case, it would be a welcome addition I think.

**Comment by idleberg** [comment]
I'm sure it's possible, but I'm not sure how. The syntax definition is taken from the [AppleScript TextMate bundle](https://github.com/textmate/applescript.tmbundle).

**Comment by nicolinuxfr** [comment]
OK great to know it's possible. I'm not sure I will be able to help either though…

**Comment by arin8000** [comment]
@idleberg it would be so helpful to have this feature! I think sublime has this. Thank you for all the work 👍

**Comment by arin8000** [comment]
@idleberg any luck on this?
