### ISSUE TITLE
Error: command 'extension.jxa.run' not found

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [idleberg/vscode-applescript#16]
I have v0.16.0 installed. I installed it via VSCode's Extensions tab/sidebar. Obviously I'm running on a Mac.

![image](https://user-images.githubusercontent.com/36159830/64136736-ae101480-cda8-11e9-867e-310566f97788.png)

When I use the command "JXA: Run Script", I get this error:

> command 'extension.jxa.run' not found

Any ideas? Thanks.

**Comment by idleberg** [comment]
The command is only available when working in "JavaScript for Automation (JXA)" has been selected.

![Screenshot 2019-09-03 at 10 12 39](https://user-images.githubusercontent.com/1504938/64155629-6da9a880-ce33-11e9-87ef-d79d3d96bd7b.png)

This is done automatically, when your document has the file-extension `*.jxa` (which might be unconventional, I don't know). When working with `*.js` files you need to switch the syntax manually.

**Comment by TheNewbieWoodworker** [comment]
Thanks! Solved the problem. Nice work, byt the way, and I really appreciate it!
