### ISSUE TITLE
Running the same command in script editor and vs code give different results. 

### ISSUE THREAD

**Issue by NylonDiamond** [idleberg/vscode-applescript#19]
When I run the exact same Applescript in script editor vs VS Code I get different results. VS Code doesn't launch the application but script editor does. Any ideas?

![image](https://user-images.githubusercontent.com/19392284/68553582-7be9e700-03d7-11ea-9710-2d72838d7e29.png)

**Comment by idleberg** [comment]
Did you save the code prior to running it?
