### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by landonwaldner** [idleberg/vscode-applescript#2]
After installing this extension, I can't run any of the commands. I get this error message.
command 'extension.applescript.compile' not found

I get the same error message for all four of the commands.

**Comment by idleberg** [comment]
How did you install the extension? What's your OS?

**Comment by landonwaldner** [comment]
I used the quick open and copied the install command. i'm using os x el capitan 10.11.5

**Comment by idleberg** [comment]
I wish I could reproduce this. I'm using the extension on OS X 10.9, 10.12 (before that 10.11), and Windows 10. I just wiped `~/.vsce` and `~/.vscode` and reinstalled the extension – still works.

Did you try any other extensions that provide commands, not just snippets?

**Comment by landonwaldner** [comment]
I'm going to upgrade to 10.12 Sierra and try it then get back to you.

**Comment by idleberg** [comment]
As I said, when I released the extension, I was still on El Capitan. I doubt that an upgrade to Sierra will change anything. The error has to be elsewhere. Did you try the obvious, like removing and re-installing? Are there additional messages in the console?

**Comment by landonwaldner** [comment]
Okay, so I figured out what was going on. In the applescript script editor, you can save your scripts as a binary which gives it a .scpt extension. But these binary files don't open in visual studio code for editing. So, I made the mistake of trying to recreate the script in VSC and just add a .scpt extension to the end when I saved it. That's where I ran into trouble and it wouldn't find the extension commands when I tried to run them.

The solution is to create a text script with an .applescript extension so that it is in text format. I can do this either in apple's script editor and save as the "Text" option instead of the script option or I can do this directly in visual studio code. When I do it like this, the extension commands work perfectly.

**Comment by idleberg** [comment]
Thanks for looking into it. I know the Atom package for AppleScript passes .scpt files to `osadecompile`. I'll see that I add this functionality in a future version.
