### ISSUE TITLE
AutoComplete feature does not work

### ISSUE THREAD

**Issue by guileschool** [idleberg/vscode-applescript#20]
I wanted to input 'activate' using autocomplete But it does not work
When I started the second snippet before the first snippet is complete, the AutoComplete feature does not work

![2019-12-04 08-58-57_2](https://user-images.githubusercontent.com/13443496/70100993-e872a180-1676-11ea-8151-311b05c7c1f9.gif)

**Comment by idleberg** [comment]
For reasons beyond my comprehension, this is the default setting for snippets in Visual Studio Code.

You have two options:

1. Press <kbd>Ctrl</kbd>+<kbb>Space</kbd> to force the the snippet suggestion dialog to pop-up

2. Disable the setting:

![Screenshot 2019-12-04 at 22 39 02](https://user-images.githubusercontent.com/1504938/70183993-30311180-16e7-11ea-8f8e-898f45eb4252.png)

**Comment by guileschool** [comment]
I like it ❤️ thank you~
