### ISSUE TITLE
Disable Toolbar buttons

### ISSUE THREAD

**Issue by LeonardoGentile** [idleberg/vscode-applescript#22]
Hello, 
is it possible to disable the buttons added by the extension? Or at least to enable them only for apple script extensions? I have no interest in using them when I'm editing a js or py file.
![image](https://user-images.githubusercontent.com/412061/84922723-8df6db00-b0c6-11ea-8c66-77d2f5d9ba2f.png)

**Comment by idleberg** [comment]
The buttons are meant to be available in JavaScript, but certainly not in Python (I don't have them!) For me there are one single requisite that need to be fulfilled, before those buttons are removed when working with JavaScript files: the JXA scope (`source.javascript.jxa`) must have access to all JavaScript features that VSCode (or an extension) exposes when working in the JavaScript scope (`source.javascript`).
