### ISSUE TITLE
Debugging AppleScript?

### ISSUE THREAD

**Issue by Detnator-Neo** [idleberg/vscode-applescript#25]
Is there any way this plugin does, or can, do AppleScript debugging (perhaps similar to [Late Night Software's Script Debugger](https://latenightsw.com))?

Two things here:
1. I can't seem to find any way that it does it already, but want to check I'm not missing anything.  
2. If that's right and it doesn't currently do it, what would it take to get it to do it?

To really clarify, in case there's any ambiguity:  I'm looking/hoping for an experience that's similar to VSCode's built in Node debugging (but with AppleScript of course).

If it's not already possible, I imagine it's a lot of work, but... I'll bet I'm not the only one who would really like this. 

Does this somehow do this already and I'm missing it?  Or if not, is it possible to add this?

Thanks!

**Comment by joeasks** [comment]
I suppose no answers to this question in the past 17 days means this extension does not provide any AppleScript debugging?
I was hoping for the developer response to this question.

**Comment by idleberg** [comment]
I'm not aware of possibilities, e.g. CLI tools, to debug AppleScript files
