### ISSUE TITLE
Support osascript shebang

### ISSUE THREAD

**Issue by rattrayalex** [idleberg/vscode-applescript#27]
## Summary

A file with no extension, but with an `osascript` shebang, should be highlighted as AppleScript:

```applescript
#!/usr/bin/env osascript

tell application "Terminal"
  do script ""
end tell
```

## Motivation

I have a `./dev` script that I don't want to add a `.applescript` extension to.

**Comment by idleberg** [comment]
Great idea, added in v0.21.0

**Comment by rattrayalex** [comment]
That was quick – thank you!
