### ISSUE TITLE
Plz add changelog

### ISSUE THREAD

**Issue by fzzr-** [idleberg/vscode-applescript#3]
![screen shot 2017-01-21 at 14 52 09](https://cloud.githubusercontent.com/assets/888526/22174182/35511d3c-dfe9-11e6-8eb3-f61f9dae29ac.png)

**Comment by idleberg** [comment]
I'll leave this issue open as a reminder. Unless there are any bugs, I don't plan a new release before Microsoft introduces an API that allows me to implement a decoder for binary scripts.

**Comment by idleberg** [comment]
This should be fixed (and working) as of 0.5.3
