### ISSUE TITLE
Syntax highlighting for Markdown Fenced Code

### ISSUE THREAD

**Issue by drkvogel** [idleberg/vscode-applescript#32]
I was hoping that this extension would syntax-highlight code in Markdown fenced code in `.md` files, e.g.:

```applescript
tell application "Finder" to get the name of front Finder window
```

but it doesn't seem to. Is this something it can support? Are there changes to `settings.json` that I need to make to enable this?

(btw I notice that AppleScript is syntax-highlighted here in GitHub!)

**Comment by idleberg** [comment]
Great idea, didn't know this was possible. Added in v0.22.0
