### ISSUE TITLE
Screenshot broken in VSCode extension view

### ISSUE THREAD

**Issue by claylo** [idleberg/vscode-applescript#33]
When viewing this extension inside VS Code, the screenshot does not appear.

Thank you for writing the extension!!

![Screenshot 2023-07-04 at 9 02 22 AM](https://github.com/idleberg/vscode-applescript/assets/33251/62bb9f45-3739-4c25-b68c-065ec962e483)

**Comment by idleberg** [comment]
Thanks for reporting. This was probably a glitch in the publishing pipeline and was fixed after pushing a new release.
