### ISSUE TITLE
How do you stop a script after starting it? 😂

### ISSUE THREAD

**Issue by lopugit** [idleberg/vscode-applescript#36]
Amazing extension wow, a little more documentation about how it works and runs would be amazing?! 

And if it's possible to view log outputs??

But yes, do you know how to stop a script besides through activity monitor? 😂

Thank you so much 🙏

**Comment by idleberg** [comment]
Have you tried the "AppleScript: Terminate Process" command?

**Comment by lopugit** [comment]
@idleberg 

Oh my word how did I miss that 🙄

I'm so sorry, and thank you again for making this extension it's pure bliss 🙏 

Let's you get copilot autocomplete and it's BANGIN 💯



**Comment by lopugit** [comment]
@idleberg yeah this works nicely! Amazing 🙏

This is my first time apple scripting and it's quite incredible 👀

```
set logFile to (open for access POSIX file "/Users/lopu/things/code/lopugit/countdown/countdown.log" with write permission)

write "Running" & return to logFile starting at eof
```
