### ISSUE TITLE
not opening code 

### ISSUE THREAD

**Issue by CastroSATT** [idleberg/vscode-applescript#37]
installed extention and used it on .scrpt files and i just get a loading bar on the tab and nothing actuallly loads or is viewable

**Comment by idleberg** [comment]
Duplicate of #34

**Comment by jetjo** [comment]
现在仍然没有解决这个问题,
在vscode中单击“xx.scpt”文件,
编辑器一直处于加载中

**Comment by jetjo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
