### ISSUE TITLE
JXA stopped working

### ISSUE THREAD

**Issue by chrillek** [idleberg/vscode-applescript#39]
While I could run JXA scripts from VSCode previously, this now (0.26.0) results in the error
`command 'extension.jxa.run' not found`. The same happens for other JXA commands like "JXA: Open Settings". The language of the edited file is set to "JavaScript for Automation". 

How can I fix that?

**Comment by idleberg** [comment]
This happens every time I switch the bundler. Will release a fix when I get home. Thanks for reporting!

**Comment by idleberg** [comment]
Did you have a chance yet to test the new version?

**Comment by chrillek** [comment]
Yes, that works just as it did before. Thanks a lot!
