### ISSUE TITLE
Can you use VSC Debugging with JXA Files?

### ISSUE THREAD

**Issue by JMichaelTX** [idleberg/vscode-applescript#6]
### Can you use VSC Debugging with JXA Files?

In Script Editor, this requires an elaborate, unreliable setup using Safari Debugger.
If we can use VSC, could you please provide detailed steps to do so.

Thanks.

**Comment by idleberg** [comment]
Can JXA be debugged with any of the command-line tools (e.g. `osascript`)? If that's the case, please provide some details.

**Comment by JMichaelTX** [comment]
@idleberg , thanks for your reply.  AFAIK the only way to debug JXA is using the Safari Browser Debugger, invoked from running a JXA script in the Script Editor.app.  Here is video showing how to do this:  https://youtu.be/qjse_iMJg18
