### ISSUE TITLE
Can't open .scpt files

### ISSUE THREAD

**Issue by sainho93** [idleberg/vscode-applescript#8]
Now the extension can only open applescripts which format is .applescrit, but can't open and edit .scpt file.

**Comment by idleberg** [comment]
Why do you say “Now” when this package _never_ had support to open `.scpt` and never will unless Microsoft introduces an load equivalent to [`onWillSaveTextDocument`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.onWillSaveTextDocument). VSCode does not open binary files, let alone run them through a decode function prior to opening.

You can request (or upvote) such an API method at [Microsoft/vscode](https://github.com/Microsoft/vscode/issue).
