### ISSUE TITLE
Support unsaved files

### ISSUE THREAD

**Issue by fabiospampinato** [idleberg/vscode-applescript#9]
If I open a new editor, and set the language mode to AppleScript I'm still not able to run the script until I save the actual file to the disk.

It would be great if this extension fully supported unsaved editors.

**Comment by nicolinuxfr** [comment]
I never thought it was an issue, but you're right, it would be great if the code as it is in the editor was used when running the script.

Right now, the run uses what is saved on disk, not what is the editor. If you forget to save the script before running it, the changes are not applied, which is weird.

So if it is possible, it would be a great addition ! 👍

**Comment by fabiospampinato** [comment]
I think it's definitely possible, the extension could just copy the content of the editor, save it automatically in a temporary file, and execute that.

**Comment by nicolinuxfr** [comment]
I tried the update, but it does not seem to work for my case, unsaved changes are still not used when running the script.

Have I missed something ?

**Comment by idleberg** [comment]
> Have I missed something ?

There were two broken 0.11 releases, but as of 0.12, I had no problems (tested on two Macs)

**Comment by idleberg** [comment]
Been away for a couple of days, what's the status on this? Everything works fine for me:

![demo](https://user-images.githubusercontent.com/1504938/43831010-15d3f44e-9b03-11e8-9edb-aa7086afef5c.gif)

(note the dot denoting the file as unsaved)

**Comment by nicolinuxfr** [comment]
Sorry, I did not take the time to test again. 

And sorry one more time, I realised watching your video that I was not using the correct function. 🤦‍♂️

I was using the standard "_Run code_" from VSCode and not the "_AppleScript: Run Script_" from this extension.

So now that I have changed my shortcuts, it works indeed just fine when I do not save changes. Thanks for that ! 👍

**Comment by idleberg** [comment]
@fabiospampinato This is probably a bug in `vscode`, but you can always invoke the commands provided by this package from the command palette
